# Generated by Django 6.0.6 on 2026-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_tags_alter_project_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='achievements_text',
            field=models.TextField(blank=True, help_text='One achievement per line. Leave blank if none.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('internship', 'Internship'), ('class', 'Class / Academic')], default='internship', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated tech tags, e.g. Django,React,PostgreSQL', max_length=300),
        ),
    ]
